Add workflows for the ci repo itself
bao-project/bao-ci pull request #14
Opened 2022-08-30 21:20 UTC by josecm

This PR instantiates the base workflow which includes the gitlint, license, yamllint and pylint checks o these checks are also ran on PRs in the bao-ci repo itself.

Also it adds a workflow that automates the build and publishing of the docker image to Docker Hub if an accepted PR contains modifications to the Dockerfile. The Docker Hub login secrets (user name and token) were already created for the repository.

2022-09-09 15:38 UTC, danielRep requested changes
The directory for the workflow .yml files are missing a `workflows` directory, i.e., `.github/workflows/base-ci.yml`

Please amend the typo `instantiante`on [fa80566](https://github.com/bao-project/bao-ci/pull/14/commits/fa80566782c06b974be09a990a0f2167d4d49877) commit

2022-09-16 12:22 UTC, josecm commented
@danielRep I've address your change requests.

@AfonsoSantos96 can you please add your review?

2022-09-16 12:45 UTC, AfonsoSantos96 approved these changes

2022-09-16 14:52 UTC, danielRep commented
The pylint check is still failing. Need to solve it, before I accept. @josecm will send a PR to fix this, and after it it's merged to the main, this PR can be rebased and the pylint check won't fail.

2022-09-16 14:55 UTC, danielRep approved these changes

2022-09-16 14:56 UTC, merged