ci: add python libraries
bao-project/bao-ci pull request #15
Opened 2022-09-09 12:17 UTC by Diogo21Costa

2022-09-10 13:20 UTC, josecm requested changes
Could you change the git message so to use a tag indicating this is a docker change. If we use `ci`as a tag here, we'll be using it for all commits, which kind of defeats the point.

2022-09-10 16:07 UTC, AfonsoSantos96 approved these changes

2022-09-12 10:33 UTC, AfonsoSantos96 reviewed
Maybe use "update (docker): add python libraries" on both commit and PR

2022-09-14 12:10 UTC, josecm approved these changes

2022-09-14 12:18 UTC, merged