fix(workflows/gitlint): use different base commit for different triggers
bao-project/bao-ci pull request #26
Opened 2022-09-19 18:46 UTC by josecm

Otherwise the check we fail if we are not on a PR, since 'github.event.pull_request.base.sha' is not defined when a workflow is triggered on a push to main or manually via workflow_dispatch.

Signed-off-by: Jose Martins <josemartins90@gmail.com>

2022-09-19 18:46 UTC, josecm commented
@bao-project/maintainers should update their repos according to this PR.

2022-09-20 08:26 UTC, AfonsoSantos96 submitted a review, later dismissed

2022-09-23 08:35 UTC, miguelafsilva5 requested changes
Seems to be an error in multiple lines. It should be `make gitline` and not `make gitline`.

2022-09-23 13:15 UTC, josecm commented
> Seems to be an error in multiple lines. It should be `make gitline` and not `make gitline`.

`make gitlint` you mean.. ahahha

Thanks for catching this. Forced pushed the correction.

2022-09-24 11:33 UTC, AfonsoSantos96 approved these changes

2022-09-26 11:03 UTC, miguelafsilva5 approved these changes

2022-09-26 11:03 UTC, merged