feat/gh-templates: add templates for PRs/Issues and provision the repo with templates
bao-project/bao-ci pull request #28
Opened 2022-10-21 17:41 UTC by danielRep

## PR Description

This change is introduced to add a PR and issues template for the bao-ci repository. Moreover, a new folder has created in `.github` to aggregate general templates to be used by other maintainers on their own repos. 

### Type of change

- **feat**: introduces a new functionality
  - Logical unit: PR and Issues templates

## Checklist:

- [x] The changes generate no new warnings when building the project. If so, I have justified above.
- [x] I have run the CI checkers before submitting the PR to avoid unnecessary runs of the workflow.

2022-10-26 09:46 UTC, miguelafsilva5 commented on .github/pull_request_template.md
> +- The PR changes adds new tests...
```suggestion
- The PR changes or adds new tests...
```

2022-10-26 09:47 UTC, miguelafsilva5 commented on .github/templates/pull_request_template.md
> +- The PR changes adds new tests...
```suggestion
- The PR changes or adds new tests...
```

2022-10-26 09:49 UTC, miguelafsilva5 requested changes
Please address the two lines pointed. Both contain a small writing mistake.

2022-10-26 15:36 UTC, miguelafsilva5 approved these changes

2022-10-31 12:34 UTC, AfonsoSantos96 approved these changes

2022-10-31 17:43 UTC, merged