feat(clang): Add llvm, clang and linker
bao-project/bao-ci pull request #83
Opened 2024-07-26 14:00 UTC by DavidMCerdeira

This PR adds as LLVM to the Bao docker in preparation for clang support in Bao.

2024-07-26 14:46 UTC, josecm approved these changes

2024-07-26 14:47 UTC, josecm requested changes
To keep inline with the commit history, the message should be `feat(docker): ...`

2024-07-26 16:25 UTC, DavidMCerdeira commented
@josecm update the commit title

What are your thoughts on having the variable `ARG CLANG_VERSION=18` only be applied to clang-format while we are installing the clang as well?

2024-08-21 13:53 UTC, josecm commented
@DavidMCerdeira add a fixed version of clang itself too

2024-08-21 13:57 UTC, AfonsoSantos96 approved these changes

2024-08-21 17:13 UTC, AfonsoSantos96 approved these changes

2024-08-22 10:45 UTC, danielRep approved these changes

2024-08-22 10:45 UTC, josecm approved these changes

2024-08-22 10:48 UTC, merged